# makefile 1
# hellomake: hellomake.c hellofunc.c
#	gcc -o hellomake hellomake.c hellofunc.c# -I.

# makefile 2
CC=gcc
CFLAGS=-I.
hellomake: hellomake.o hellofunc.o
	 $(CC) -o hellomake hellomake.o hellofunc.o $(CFLAGS)

# makefile 3

